# Generated by Django 3.1.1 on 2020-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydcs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='temps',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.TextField(max_length=4500),
        ),
    ]
