# Generated by Django 3.1.1 on 2020-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydcs_app', '0002_auto_20200917_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='temps',
            field=models.CharField(max_length=100),
        ),
    ]
