# Generated by Django 3.1.1 on 2020-09-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydcs_app', '0004_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='essai',
            name='coursValid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essai',
            name='cours',
            field=models.CharField(max_length=20),
        ),
    ]
