# Generated by Django 3.1.1 on 2020-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydcs_app', '0006_auto_20200922_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='essai',
            name='timesend',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
